/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewTaleRouteImport } from './routes/new-tale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaleTaleIdRouteImport } from './routes/tale/$taleId'

const NewTaleRoute = NewTaleRouteImport.update({
  id: '/new-tale',
  path: '/new-tale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaleTaleIdRoute = TaleTaleIdRouteImport.update({
  id: '/tale/$taleId',
  path: '/tale/$taleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-tale': typeof NewTaleRoute
  '/tale/$taleId': typeof TaleTaleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-tale': typeof NewTaleRoute
  '/tale/$taleId': typeof TaleTaleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new-tale': typeof NewTaleRoute
  '/tale/$taleId': typeof TaleTaleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new-tale' | '/tale/$taleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new-tale' | '/tale/$taleId'
  id: '__root__' | '/' | '/new-tale' | '/tale/$taleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewTaleRoute: typeof NewTaleRoute
  TaleTaleIdRoute: typeof TaleTaleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-tale': {
      id: '/new-tale'
      path: '/new-tale'
      fullPath: '/new-tale'
      preLoaderRoute: typeof NewTaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tale/$taleId': {
      id: '/tale/$taleId'
      path: '/tale/$taleId'
      fullPath: '/tale/$taleId'
      preLoaderRoute: typeof TaleTaleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewTaleRoute: NewTaleRoute,
  TaleTaleIdRoute: TaleTaleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
